creation_rules:
  # upon creation of a file that matches the pattern *dev.yaml,
  # KMS set A is used
  # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
  - path_regex: environments/livelihood-prod-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-2:654654556600:key/23a30979-5c60-4538-ab12-dc2dda0c7160'