creation_rules:
  # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
  - path_regex: environments/livelihood-prod-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-2:654654556600:key/23a30979-5c60-4538-ab12-dc2dda0c7160'
  - path_regex: environments/livelihood-dev-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-2:654654556600:key/192d2734-8c48-4557-8211-e803465eacf2'
  - path_regex: environments/livelihood-uat-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-2:654654556600:key/9a38a613-acfe-4c6f-b132-7392eecb37d8'