apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-new
  namespace: core
spec:
  schedule: "0 0 * * *"  #
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-new-job
            image: selcohub/cronjob-livelihood:latest-6-july-2026
            args:
              - in
          restartPolicy: OnFailure
