apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-new
  namespace: core
spec:
  schedule: "0 */2 * * *"
  timeZone: Asia/Kolkata
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-new-job
            image: selcohub/cronjob-livelihood:staging-10-july-2026-v2
            args:
              - livelihood
          restartPolicy: OnFailure
