apiVersion: batch/v1
kind: CronJob
metadata:
  name: sla-compute-job
  namespace: core
spec:
  schedule: "28 * * * *"
  timeZone: Asia/Kolkata
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sla-job
            image: selcohub/cronjob-sla-livelihood:staging-10-july-2026-v2
            args:
              - livelihood
          restartPolicy: OnFailure
