{{- with index .Values "secrets" "loki-aws" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .accesskey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .secretaccesskey | b64enc | quote }}
  {{- end }}
