# Common Labels
labels:
  app: "installation-qc"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "installation-qc"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "selcohub/installation-qc"
  tag: feature-new-components-566c04f487c1e99d97b7159228fe996e4d88c3d3
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/installation-qc/"
  readinessProbePath: "/installation-qc/"

    
extraVolumes: |
  - name: js-injection
    configMap:
      name: installation-qc

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
