name: livelihood-dev
namespace: argocd

project:
  description: Restrict ArgoCD access to core namespace
  sourceRepos:
    - https://github.com/Selco-Foundation/DevOps-Livelihood.git
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist: []
    # - group: networking.k8s.io
    #   kind: Ingress

applicationset:
  repoURL: https://github.com/Selco-Foundation/DevOps-Livelihood.git
  revision: develop
  chartRoot: deploy-as-code/charts/core-services/digit-ui
  valueFiles:
    - ../../environments/livelihood-dev.yaml
    - ../../environments/livelihood-dev-tags.yaml

  # syncPolicy:
  #   automated:
  #     prune: false
  #     selfHeal: false

  # syncOptions:
  #   - CreateNamespace=true
  #   - Validate=true
  #   - ServerSideApply=true
  #   - PruneLast=true