name: livelihood-dev
namespace: argocd

project:
  description: Restrict ArgoCD access to core namespace
  sourceRepos:
    - https://github.com/Selco-Foundation/DevOps-Livelihood.git
  destination:
    server: https://kubernetes.svc.default
    namespace: core
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
    - group: networking.k8s.io
      kind: Ingress

applicationset:
  repoURL: https://github.com/Selco-Foundation/DevOps-Livelihood.git
  revision: develop
  chartRoot: deploy-as-code/charts/core-services/*
  valueFiles:
    - ../../environments/livelihood-dev.yaml
    - ../../environments/livelihood-dev-tags.yaml
    - ../../environments/livelihood-dev-secrets.yaml
