amc-service:
  image:
    tag: v3.6.26-8bf11f800d198d8e3f10e39d49598ef2577f682f
  initContainers:
    dbMigration:
      image:
        tag: v3.6.26-8bf11f800d198d8e3f10e39d49598ef2577f682f

asset-registry:
  image:
    tag: staging-23f86f133b83491c2a174abefcee699824d4aca5
  initContainers:
    dbMigration:
      image:
        tag: staging-23f86f133b83491c2a174abefcee699824d4aca5

field-planner-activity:
  image:
    tag: v3.3.7-73d0cc3be378c4495e6f7d7162b2c5d8c1951487
  initContainers:
    dbMigration:
      image:
        tag: v3.3.7-73d0cc3be378c4495e6f7d7162b2c5d8c1951487

field-planner:
  image:
    tag: v3.3.9-2eae964f8fa251e7adba756c2b6eb1f34ea47851
  initContainers:
    dbMigration:
      image:
        tag: v3.3.9-2eae964f8fa251e7adba756c2b6eb1f34ea47851

ingestion-service:
  image:
    tag: staging-bc02f5c23776016d0482a2537d6c176420b6ba91

project:
  image:
    tag: v3.7.26-dfdf5e0e2013eb8c97531f91308a25dbfe3bd6de
  initContainers:
    dbMigration:
      image:
        tag: v3.7.26-dfdf5e0e2013eb8c97531f91308a25dbfe3bd6de

vendor-registry:
  image:
    tag: staging-e49076017baee831d2e671643096fa47866b1bc5
  initContainers:
    dbMigration:
      image:
        tag: staging-e49076017baee831d2e671643096fa47866b1bc5

installation-qc:
  image:
    tag: v3.7.26-dfdf5e0e2013eb8c97531f91308a25dbfe3bd6de

pdf-service:
  image:
    tag: pdf-2.9-lts-a17e8ebea8-48

workbench-ui:
  image:
    tag: v3.3.7-73d0cc3be378c4495e6f7d7162b2c5d8c1951487

rms-service:
  image:
    tag: v3.7.26-dfdf5e0e2013eb8c97531f91308a25dbfe3bd6de
  initContainers:
    dbMigration:
      image:
        tag: v3.7.26-dfdf5e0e2013eb8c97531f91308a25dbfe3bd6de

boundary-service:
  image:
    tag: staging-e49076017baee831d2e671643096fa47866b1bc5
  initContainers:
    dbMigration:
      image:
        tag: staging-e49076017baee831d2e671643096fa47866b1bc5

facility-service:
  image:
    tag: staging-9bc1e3667436010ab565bc4786781497106f2fe5
  initContainers:
    dbMigration:
      image:
        tag: staging-9bc1e3667436010ab565bc4786781497106f2fe5

egov-hrms:
  image:
    tag: v3.6.24-1e609f3077d20ec6cc98ef672923329c68de19a4
  initContainers:
    dbMigration:
      image:
        tag: v3.6.24-1e609f3077d20ec6cc98ef672923329c68de19a4

egov-filestore:
  image:
    tag: v2.0.3-7de51e1b5d83b29754c5e30d33c931d5cc9159aa
  initContainers:
    dbMigration:
      image:
        tag: v2.0.3-7de51e1b5d83b29754c5e30d33c931d5cc9159aa

egov-workflow-v2:
  image:
    tag: staging-d0c9ccd8b8fb5b416867bae62f3f7720924d9dd1
  initContainers:
    dbMigration:
      image:
        tag: staging-d0c9ccd8b8fb5b416867bae62f3f7720924d9dd1

im-services-analytics:
  image:
    tag: staging-e1bc2d0b7a279911d088e77cc4ecace4f57d6d5b

processor-services:
  image:
    tag: main-989d294d0111097082f14e4045f6ddcb97007235

im-services:
  image:
    tag: staging-bc62b54d4c657f2bb382238be4b642b8d7930755
  initContainers:
    dbMigration:
      image:
        tag: staging-bc62b54d4c657f2bb382238be4b642b8d7930755

livelihood-ui:
  image:
    tag: staging-84e59166b6aafd78ebac29fdbc702fea9c793ef7

digit-ui:
  image:
    tag: v3.7.26-dfdf5e0e2013eb8c97531f91308a25dbfe3bd6de

inbox:
  image:
    tag: staging-4d6a8862246502b5d5609660a7a3eb2c118701c3

egov-mdms-service:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-notification-sms:
  image:
    tag: master-03072024-1

egov-notification-mail:
  image:
    tag: v2.9.2-4a60f20

audit-service:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-accesscontrol:
  image:
    tag: v2.9.2-4a60f20

egov-enc-service:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-idgen:
  image:
    tag: v2.2.1-9dd1451c12150aca6d1bcf06565c2d6a7bb32a04

egov-indexer:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-localization:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-location:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-otp:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-url-shortening:
  image:
    tag: staging-bc62b54d4c657f2bb382238be4b642b8d7930755
  initContainers:
    dbMigration:
      image:
        tag: staging-bc62b54d4c657f2bb382238be4b642b8d7930755

egov-persister:
  image:
    tag: v2.9.2-4a60f20

egov-user:
  image:
    tag: core-2.9-lts-egov-user-deployement-c33cfe45ab-13
  initContainers:
    dbMigration:
      image:
        tag: core-2.9-lts-egov-user-deployement-c33cfe45ab-13

gateway:
  image:
    tag: gateway-form-data-whilelisting-fix-71aff8f

user-otp:
  image:
    tag: v2.9.2-4a60f20
